version: "3.9"  # optional since v1.27.0
services:
  nginx_question6:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
  php_question6:
    image: php:8-fpm
    build: 
      dockerfile: ./php/Dockerfile
    volumes:
      - ./php/index.php:/var/www/html/index.php
  mariadb_question6:
    image: mariadb:10.7
    ports:
      - "3010"
    volumes:
      - "./sql/sql.sql:/docker-entrypoint-initdb.d/sql.sql"
    env_file:
    - .env